Start-Process -FilePath "C:\Users\Jakub\AppData\Local\Postman\app-6.7.3\Postman.exe"
echo "start postman"
Start-Process -FilePath "C:/xampp56/xampp-control.exe"
echo "start xampp-controler 56v"
Start-Process -FilePath "C:\Program Files\Mailbird\Mailbird.exe"
echo "start mailbird"
Start-Process -FilePath "C:\Program Files\JetBrains\PhpStorm 2018.3\bin\phpstorm64.exe"
echo "start phpstorm"
Start-Process -FilePath "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" "example-address.test"
echo "start chrome"
Start-Process -FilePath "C:\Program Files\Notepad++\notepad++.exe"
echo "start notepad"
Start-Process -FilePath "C:\Program Files\Mozilla Firefox\firefox.exe"
echo "start firefox 1"
Start-Process -FilePath "C:\Program Files\Mozilla Firefox\firefox.exe"
echo "start firefox 2"
Start-Process -FilePath "C:\Users\Jakub\AppData\Local\slack\app-3.3.7\slack.exe"
echo "start slack"
Start-Process -FilePath "C:\Program Files\HeidiSQL\heidisql.exe"
echo "start heidisql"
Start-Process -FilePath "C:\Program Files\Git\git-bash.exe"
echo "Start git-bash"
Start-Process -FilePath "C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\Ssms.exe"
echo "start microsoft sql manager studio"
Start-Process -FilePath "C:\"
echo "start c:\"
Start-Process -FilePath "C:\web\git\example"
echo "start c:\web\git\example"
start explorer
echo "start explorer"
start taskmgr
echo "start task manager"
start powershell
echo "start powershell"
exit
