Start-Process -FilePath "C:\Users\Jakub\AppData\Local\Postman\app-7.0.7\Postman.exe"
Write-Output "start postman"
Start-Process -FilePath "C:/xampp56/xampp-control.exe"
Write-Output "start xampp-controler 56v"
Start-Process -FilePath "C:\Program Files\Mailbird\Mailbird.exe"
Write-Output "start mailbird"
Start-Process -FilePath "C:\Program Files\JetBrains\PhpStorm 2018.3\bin\phpstorm64.exe"
Write-Output "start phpstorm"
Start-Process -FilePath "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" "example.test"
Write-Output "start chrome"
Start-Process -FilePath "C:\Program Files\Notepad++\notepad++.exe"
Write-Output "start notepad"
Start-Process -FilePath "C:\Program Files\Mozilla Firefox\firefox.exe"
Write-Output "start firefox 1"
Start-Process -FilePath "C:\Program Files\Mozilla Firefox\firefox.exe"
Write-Output "start firefox 2"
Start-Process -FilePath "C:\Users\Jakub\AppData\Local\slack\app-3.3.7\slack.exe"
Write-Output "start slack"
Start-Process -FilePath "C:\Program Files\HeidiSQL\heidisql.exe"
Write-Output "start heidisql"
Start-Process -FilePath "C:\Program Files\Git\git-bash.exe"
Write-Output "Start git-bash"
Start-Process -FilePath "C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\Ssms.exe"
Write-Output "start microsoft sql manager studio"
Start-Process -FilePath "C:\"
Write-Output "start c:\"
Start-Process -FilePath "C:\web\git\example"
Write-Output "start c:\web\git\example"
Start-Process explorer
Write-Output "start explorer"
Start-Process taskmgr
Write-Output "start task manager"
Start-Process powershell
Write-Output "start powershell"
exit
